name: choclo
channels:
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - make
  # Run
  - numpy
  - numba
  # Build
  - python-build
  - twine
  # Test
  - pytest
  - pytest-cov
  - coverage
  # Documentation
  - sphinx==7.2.*
  - numpydoc>=1.8.0
  - sphinx-book-theme==1.1.*
  - sphinx-copybutton==0.5.*
  - sphinx-design==0.5.*
  - jupyter-sphinx==0.5.*
  - matplotlib
  # Style
  - ruff
  - zizmor
  - pip:
    - burocrata
