name: choclo
channels:
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - make
  # Run
  - numpy
  - numba
  # Build
  - python-build
  - twine
  # Test
  - pytest
  - pytest-cov
  - coverage
  # Documentation
  - sphinx==7.2.*
  - numpydoc==1.7.*
  - sphinx-book-theme==1.1.*
  - sphinx-copybutton==0.5.*
  - sphinx-design==0.5.*
  - jupyter-sphinx==0.5.*
  - matplotlib
  # Style
  - black
  - pathspec
  - isort
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - flake8-unused-arguments
  - pep8-naming
  - pip:
    - burocrata
    - zizmor
