# Copyright (c) 2022 The Choclo Developers.
# Distributed under the terms of the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause
#
# This code is part of the Fatiando a Terra project (https://www.fatiando.org)
#
"""
Forward modelling function for point sources
"""
from numba import jit

from ..constants import GRAVITATIONAL_CONST
from ..utils import distance_cartesian
from ._kernels import (
    kernel_e,
    kernel_ee,
    kernel_en,
    kernel_eu,
    kernel_n,
    kernel_nn,
    kernel_nu,
    kernel_pot,
    kernel_u,
    kernel_uu,
)


@jit(nopython=True)
def gravity_pot(easting_p, northing_p, upward_p, easting_q, northing_q, upward_q, mass):
    r"""
    Gravitational potential field due to a point source

    Returns the gravitational potential field produced by a single point source
    on a single computation point

    Parameters
    ----------
    easting_p : float
        Easting coordinate of the observation point in meters.
    northing_p : float
        Northing coordinate of the observation point in meters.
    upward_p : float
        Upward coordinate of the observation point in meters.
    easting_q : float
        Easting coordinate of the point source in meters.
    northing_q : float
        Northing coordinate of the point source in meters.
    upward_q : float
        Upward coordinate of the point source in meters.
    mass : float
        Mass of the point source in kilograms.

    Returns
    -------
    potential : float
        Gravitational potential field generated by the point source on the
        observation point in :math:`\text{J}/\text{kg}`.

    Notes
    -----
    Returns the gravitational potential field :math:`V(\mathbf{p})` on the
    observation point :math:`\mathbf{p} = (x_p, y_p, z_p)` generated by
    a single point source located in :math:`\mathbf{q} = (x_q, y_q, z_q)` and
    mass :math:`m`.

    .. math::

        V(\mathbf{p}) = G m \frac{1}{\lVert \mathbf{p} - \mathbf{q} \rVert^2}

    where :math:`\lVert \cdot \rVert_2` refer to the :math:`L_2` norm (the
    Euclidean distance between :math:`\mathbf{p}` and :math:`\mathbf{q}`)
    and :math:`G` is the Universal Gravitational Constant.
    """
    distance = distance_cartesian(
        easting_p, northing_p, upward_p, easting_q, northing_q, upward_q
    )
    kernel = kernel_pot(
        easting_p, northing_p, upward_p, easting_q, northing_q, upward_q, distance
    )
    return GRAVITATIONAL_CONST * mass * kernel


@jit(nopython=True)
def gravity_e(easting_p, northing_p, upward_p, easting_q, northing_q, upward_q, mass):
    r"""
    Easting component of the gravitational acceleration due to a point source

    Returns the easting component of the gravitational acceleration produced by
    a single point source on a single computation point

    Parameters
    ----------
    easting_p : float
        Easting coordinate of the observation point in meters.
    northing_p : float
        Northing coordinate of the observation point in meters.
    upward_p : float
        Upward coordinate of the observation point in meters.
    easting_q : float
        Easting coordinate of the point source in meters.
    northing_q : float
        Northing coordinate of the point source in meters.
    upward_q : float
        Upward coordinate of the point source in meters.
    mass : float
        Mass of the point source in kilograms.

    Returns
    -------
    g_e : float
        Easting component of the gravitational acceleration generated by the
        point source on the observation point in :math:`\text{m}/\text{s}^2`.

    Notes
    -----
    Returns the easting component :math:`g_x(\mathbf{p})` of the gravitational
    acceleration :math:`\mathbf{g}` on the observation point :math:`\mathbf{p}
    = (x_p, y_p, z_p)` generated by a single point source located in
    :math:`\mathbf{q} = (x_q, y_q, z_q)` and mass :math:`m`.

    .. math::

        g_x(\mathbf{p}) = - G m
            \frac{
                x_p - x_q
            }{
                \lVert \mathbf{p} - \mathbf{q} \rVert^2
            }

    where :math:`\lVert \cdot \rVert_2` refer to the :math:`L_2` norm (the
    Euclidean distance between :math:`\mathbf{p}` and :math:`\mathbf{q}`)
    and :math:`G` is the Universal Gravitational Constant.
    """
    distance = distance_cartesian(
        easting_p, northing_p, upward_p, easting_q, northing_q, upward_q
    )
    kernel = kernel_e(
        easting_p, northing_p, upward_p, easting_q, northing_q, upward_q, distance
    )
    return GRAVITATIONAL_CONST * mass * kernel


@jit(nopython=True)
def gravity_n(easting_p, northing_p, upward_p, easting_q, northing_q, upward_q, mass):
    r"""
    Northing component of the gravitational acceleration due to a point source

    Returns the northing component of the gravitational acceleration produced by
    a single point source on a single computation point

    Parameters
    ----------
    easting_p : float
        Easting coordinate of the observation point in meters.
    northing_p : float
        Northing coordinate of the observation point in meters.
    upward_p : float
        Upward coordinate of the observation point in meters.
    easting_q : float
        Easting coordinate of the point source in meters.
    northing_q : float
        Northing coordinate of the point source in meters.
    upward_q : float
        Upward coordinate of the point source in meters.
    mass : float
        Mass of the point source in kilograms.

    Returns
    -------
    g_e : float
        Northing component of the gravitational acceleration generated by the
        point source on the observation point in :math:`\text{m}/\text{s}^2`.

    Notes
    -----
    Returns the northing component :math:`g_y(\mathbf{p})` of the gravitational
    acceleration :math:`\mathbf{g}` on the observation point :math:`\mathbf{p}
    = (x_p, y_p, z_p)` generated by a single point source located in
    :math:`\mathbf{q} = (x_q, y_q, z_q)` and mass :math:`m`.

    .. math::

        g_y(\mathbf{p}) = - G m
            \frac{
                y_p - y_q
            }{
                \lVert \mathbf{p} - \mathbf{q} \rVert^2
            }

    where :math:`\lVert \cdot \rVert_2` refer to the :math:`L_2` norm (the
    Euclidean distance between :math:`\mathbf{p}` and :math:`\mathbf{q}`)
    and :math:`G` is the Universal Gravitational Constant.
    """
    distance = distance_cartesian(
        easting_p, northing_p, upward_p, easting_q, northing_q, upward_q
    )
    kernel = kernel_n(
        easting_p, northing_p, upward_p, easting_q, northing_q, upward_q, distance
    )
    return GRAVITATIONAL_CONST * mass * kernel
