# Copyright (c) 2022 The Choclo Developers.
# Distributed under the terms of the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause
#
# This code is part of the Fatiando a Terra project (https://www.fatiando.org)
#
# Import functions/classes to make the public API
"""
These are the modules, functions, and classes that make up the Choclo API.

Here you will find the list of available utilities as well as kernel and
forward modelling functions for gravity and magnetic fields generated by
different types of sources.
"""

from . import constants, dipole, point, prism, utils
from ._version import __version__

# Append a leading "v" to the generated version by setuptools_scm
__version__ = f"v{__version__}"
